### ISSUE TITLE
Camera follow and/or screen transitions

### ISSUE THREAD

**Issue by rustrix** [DaltonSW/MetroidvaniaMonth23#45]
Depends on how MetSys handles screens: #30

- [ ] At least have the camera follow the character similar to EnviroMetal.

Optional features:
- [ ] Camera becomes offset when the character is moving, to show more of the area in front of the character than behind.
- [ ] Camera is locked into the level boundaries, to avoid showing out-of-bounds areas. (implemented in EnviroMetal)
- [ ] If there will be hard barriers between screens (like Celeste), add screen transition animation to keep it from being jarring (fade-to-black)

**Comment by DaltonSW** [comment]
MetSys touts a 'screen transition' system, so I think that kind of thing will be reasonably handled for us. 

Camera following can maybe be yoinked directly from EM

**Comment by DaltonSW** [comment]
Both are handled by MetSys and PR #91
