### ISSUE TITLE
World 2 Boss

### ISSUE THREAD

**Issue by rustrix** [DaltonSW/MetroidvaniaMonth23#46]
Design the World 2 (Outdoors #23 ) boss.

**Comment by rustrix** [comment]
The boss is going to give you Double Dash as the reward. I feel like they should use the double-dash, or a mega-dash, or at least be fast. Thinking Tracer from Overwatch, Ingenium from My Hero Academia, Red from Transistor. Cyborg speed.

I'm liking the idea of this boss *not* being a cyborg monstrosity, since they'll be dashing. A big sprite dashing across the screen wouldn't leave much room to maneuver. So something human-sized.

Maybe they're an enemy of the cult.
- A rival cult's agent?
- A rebel/punk from a group the cult subjugates?
- An android controlled by the demon?

Something very like Tracer, but with robot legs+exoskeleton instead of time-powers. With 2-3 power cells which recharge independently and must be discharged all at once. A very anime kind of high-skilled villain or anti-hero who trained for years to master this gear.

**Comment by rustrix** [comment]
A enemy with a blink similar to the player's seems like a nightmare when working out the interactions between your dashes. Plus, it might be hard to read a situation where you're both dashing at each other a bunch.

Would definitely like to try that, but for the sake of time, I think this boss should just do a flurry of screen-wide dashes. For each dash, they'd become invincible, telegraph the path they're going to travel, then create a hitbox along that path. Then they'd stay stuck at the end for a while in a vulnerable state. So the player is incentivized to both dodge the path and try to maneuver to its endpoint at the same time, creating a dynamic platforming challenge.

I have an idea for a sniper enemy for World 2 which behaves similarly. It would be like Sans Undertale's "Gaster Blaster" attacks, or the laser turrets in N+, where the enemy takes aim on you, waits locked on for a second so you can get out of the way, then fires. So you need to move out of the path and also keep moving. Having the sniper enemy introduced in World 2 and making the boss have a similar move would rhyme nicely.

**Comment by patrick-webdev** [comment]
Deadline Goal: 03/13
